### ISSUE TITLE
Change webservice URL

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/wikipathways-api-client-py#1]
Looks great! Quick comment: you are using the following URL (http://www.wikipathways.org/wpi/webservicetest/). We decided that we will use the following URL in the future: http://webservice.wikipathways.org. This should not require any changes except for simpler function calls:

 response = requests.get(self.base_iri + '?method=getPathwayInfo&format=xml', params=request_params)

 response = requests.get(self.base_iri + 'getPathwayInfo', params=request_params)

The method and format is not needed anymore.

**Comment by mkutmon** [comment]
This should be fixed with commit: https://github.com/wikipathways/wikipathways-api-client-py/commit/5ad584a40a9b53b196a3e0955768adece67ec33e

Please check and close this issue if this is okay.

**Comment by ariutta** [comment]
Awesome. That looks good. Thanks.
