### ISSUE TITLE
get_pathway_as return type

### ISSUE THREAD

**Issue by guillermomarco** [wikipathways/wikipathways-api-client-py#2]
Hi! I just started migrating my scripts to your brand new Wikipathways Python API :)

I'm running some of the examples, to test and debug new services return to adapt my scripts.
Using get_pathway_as, I was expecting to get a raw result string of the specified "fileType".

``` python
        if request_params['fileType'] == 'gpml' or request_params['fileType'] == 'owl' or request_params['fileType'] == 'svg':
            response = ET.fromstring(response_string)
        else:
            response = response_string
```

I notice what I really want is the "raw" `response_string` to write it to a local *.gpml file. However I would like to understand what's the response I'm getting from `ET.fromstring(response_string)`.

This is the return object I'm getting, I don't understand what can I do with this or how to extract or print it to file. I'm new to lxml so excuse me if it's an obvious question.
![return_pathway](https://cloud.githubusercontent.com/assets/2011448/6388534/406f4f30-bd9b-11e4-9934-1327bb81eff8.png)

Thanks!

**Comment by ariutta** [comment]
Hi Guillermo,

It's a fair question - multiple users have said the lxml etree response is confusing. So I'm actually going to update the lib to just return a plain string. Specifically in response to the lxml question, however, etree has a "tostring" method for serialization.

Anders 

----- Original Message -----

**Comment by guillermomarco** [comment]
Awesome! Can't wait for those changes.

**Comment by ariutta** [comment]
I updated it now, so it should return what you would expect.
