### ISSUE TITLE
find_pathways_by_xref returning duplicated pathways

### ISSUE THREAD

**Issue by guillermomarco** [wikipathways/wikipathways-api-client-py#3]
I'm getting duplicated pathways when querying WS using `find_pathways_by_xref` ws.

``` python
    wikipathways_api_client_instance = WikipathwaysApiClient()
    kwargs = {
        '@id': [
            'http://identifiers.org/ensembl/ENSG00000012048',
        ]
    }
    pathways_by_xref = wikipathways_api_client_instance.find_pathways_by_xref(**kwargs)
    print pathways_by_xref
```

 However the origin of this bug is on WS and not python api, maybe `find_pathways_by_xref` could be modified to check if a pathway with same identifier has already been added to the `pathways` list as a temporal fix.

This seems to work for what I've tested.

``` python
            if not any(p['identifier'] == pathway['identifier'] for p in pathways):
                pathways.append(pathway)
```

**Comment by ariutta** [comment]
Thanks. I added your temporary fix to the lib and will forward the WS issue to the appropriate person.
